### PR TITLE
Reimplement regex library using std::regex underneath

### PR DESCRIPTION
**Pull request by timwoj**

### CODE REVIEW

**Comment by timwoj** [comment]
This should resolve https://github.com/robinrowe/libunistd/issues/10 as well.

**Comment by timwoj** [comment]
Ping on this?

**Comment by robinrowe** [comment]
Good idea. Needs a minor update: include copyright/license header. See Contributors section of libunistd README.md for details.

**Comment by timwoj** [comment]
Fixed the copyright header and removed the use of `#pragma once`.

**Review by robinrowe — APPROVED** [review]
Thank you.

**Pull request merged**
